
services:
  smartfence_analyticsmanagement1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartfence_analyticsmanagement1
    expose:
      - ${PROD_PORT} 
    env_file:
      - .env
    environment:
      - GO_ENV=development
      - SERVICE_ID=smartfence_analyticsmanagement1
      - MODE=production
      - PROD_PORT=${PROD_PORT}
      - DEV_PORT=${DEV_PORT}
    networks:
      - smartfence_analyticsmanagement_network
      - databaseservice_smartfence_database_network

  smartfence_analyticsmanagement2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartfence_analyticsmanagement2
    env_file:
      - .env
    expose:
      - ${PROD_PORT}
    environment:
      - GO_ENV=development
      - SERVICE_ID=smartfence_analyticsmanagement2
      - MODE=production
      - PROD_PORT=${PROD_PORT}
      - DEV_PORT=${DEV_PORT}
    networks:
      - smartfence_analyticsmanagement_network
      - databaseservice_smartfence_database_network

  smartfence_nginx_analyticsmanagement:
    image: nginx:latest
    container_name: smartfence_nginx_analyticsmanagement
    ports:
      - "${WEBSERVER_PORT}:80"
    env_file:
      - .env
    volumes:
      - ./nginx/app.conf.template:/etc/nginx/conf.d/app.conf.template
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    depends_on:
      - smartfence_analyticsmanagement1
      - smartfence_analyticsmanagement2
    networks:
      - smartfence_analyticsmanagement_network
      - databaseservice_smartfence_database_network

networks:
  smartfence_analyticsmanagement_network:
    driver: bridge
  
  databaseservice_smartfence_database_network:
    external: true

volumes:
  dbdata:
    driver: local
  local_pgdata:
  pgadmin-data:
