FROM --platform=linux/amd64 nginx:latest

COPY ./entrypoint.sh /entrypoint.sh
COPY ./nginx/app.conf.template /etc/nginx/conf.d/default.conf

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
