
services:
  smartfence_webservice:
    image: nginx:latest
    container_name: nginx-smartfence-landing-webservice
    ports:
      - "${LANDING_PORT}:80"  # Expose the desired port to localhost (20884)
    env_file:
      - .env
    volumes:
      - ./nginx/app.conf.template:/etc/nginx/conf.d/app.conf.template  # Make sure the Nginx config is correct
      - ./entrypoint.sh:/entrypoint.sh
      - ./nginx/ssl:/etc/nginx/ssl
      - ./html:/usr/share/nginx/html  # Ensure the HTML files are correctly mounted
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    networks:
      - hardwareservice_app_network
      - smartfence_landing_webservice_network
      - usersmanagement_smartfence_usersmanagement_network
      - devicesmanagement_smartfence_devicemanagement_network
      - analyticsmanagement_smartfence_analyticsmanagement_network

  smartfence_nginx_landingpage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartfence_nginx_landingpage
    networks:
      - smartfence_landing_webservice_network
      - devicesmanagement_smartfence_devicemanagement_network
    environment:
      - NODE_ENV=production
    expose:
      - "4173"  # Expose port 4173 for internal communication, not external
    # No need for `ports` here since we're using `expose`
    # We're allowing the `nginx-smartfence-landing-webservice` container to reach this port internally
    command: ["http-server", "dist", "--port", "4173"]  # Make sure Vite app is running on port 4173

networks:
  smartfence_landing_webservice_network:
    driver: bridge
  
  devicesmanagement_smartfence_devicemanagement_network:
    external: true
  
  usersmanagement_smartfence_usersmanagement_network:
    external: true

  analyticsmanagement_smartfence_analyticsmanagement_network:
    external: true

  hardwareservice_app_network:
    external: true

